apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Svc.Admin.name }}
spec:
  selector:
    app: {{ .Values.Svc.Admin.name }}
  ports:
    - port: {{ .Values.Svc.Admin.port }}  
      targetPort: {{ .Values.Svc.Admin.target_port }}
  type: {{ .Values.Svc.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Svc.Web.name }}
spec:
  selector:
    app: {{ .Values.Svc.Web.name }}
  ports:
    - port: {{ .Values.Svc.Web.port }}  
      targetPort: {{ .Values.Svc.Web.target_port }}
  type: {{ .Values.Svc.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Svc.Cronjob.name }}
spec:
  selector:
    app: {{ .Values.Svc.Cronjob.name }}
  ports:
    - port: {{ .Values.Svc.Cronjob.port }}  
      targetPort: {{ .Values.Svc.Cronjob.target_port }}
  type: {{ .Values.Svc.type }}